version: '3.9'
services:
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /front-end
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /back-end
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=localhost
      - DB_PORT=3002
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: sameersbn/postgresql:12-20200524
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:5432
    environment:
      - PG_PASSWORD=password
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=NG_CASH
    restart: 'always'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE
